### ISSUE TITLE
fc-presets doesn't work

### ISSUE THREAD

**Issue by nicber** [drenninghoff/infinality-ultimate-fedora#2]
This is the error I get when I use fc-presets:

```
[nicolas@localhost ~]$ /usr/bin/fc-presets set
1) combi
2) free
3) ms
4) reset
5) quit
Enter your choice... 3
 [ ms ] preset chosen...
/usr/bin/fc-presets: line 139: pushd: /etc/fonts/conf.avail.infinality: No such file or directory
ls: cannot access ms/*-ms.conf: No such file or directory
Target not found. Did you set up
fontconfig-infinality-ultimate correctly?
```

The files it needs are actually installed in `/usr/share/fontconfig/`.
BTW Thanks for your work!

**Comment by danielrenninghoff** [comment]
Thanks for the bug report. I haven't thought about that, because I don't use the fc-presets tool. I've build a new version fontconfig-infinality-ultimate-2.11.94-4 that should fix the issue. If you don't see this version, try running "sudo dnf clean metadata" before updating. :)

**Comment by nicber** [comment]
Thanks! It is fixed now.
Another problem I found is that it does not install the infinality-settings.sh file in /etc/profile.d/ as 
I interpret it should. Look at the docs in the section "If you still prefer or have to go the generic way",
in https://github.com/bohoomil/fontconfig-ultimate
Thanks :)

**Comment by danielrenninghoff** [comment]
Thanks, but my package actually installs infinality-settings.sh in /etc/X11/xinit/xinitrc.d/, so it is run everytime X starts. This is in line with freetype-infinality-ultimate on Arch Linux. You can check that it works by running for example "echo $INFINALITY_FT_USE_VARIOUS_TWEAKS" in a terminal :).
