### ISSUE TITLE
gtk2.686 requires libcairo

### ISSUE THREAD

**Issue by JHK** [drenninghoff/infinality-ultimate-fedora#3]
Hi, I think this it is a similar issue to #1. When I want to install steam or skype they need gtk2.i686. Installing that fails with:

```
~ # dnf install gtk2.i686
Last metadata expiration check performed 0:13:45 ago on Fri Nov 27 08:26:48 2015.
Error: package gtk2-2.24.28-2.fc23.i686 requires libcairo.so.2, but none of the providers can be installed
(try to add '--allowerasing' to command line to replace conflicting packages)
```

**Comment by danielrenninghoff** [comment]
Thanks for your bugreport. The problem with this is, that Copr doesn't support multilib packages by default, so the dependency resolution f*cks up somewhere. For it to work you need to manually edit the _copr_dnlrn-infinality-ultimate.repo file in /etc/yum.repos.d/ as outlined in here: https://fedorahosted.org/copr/wiki/UserDocs#Multilib

It should look like this afterwards:

```
[dnlrn-infinality-ultimate-i386]
name=Copr repo for infinality-ultimate owned by dnlrn (i386)
baseurl=https://copr-be.cloud.fedoraproject.org/results/dnlrn/infinality-ultimate/fedora-$releasever-i386/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/dnlrn/infinality-ultimate/pubkey.gpg
enabled=1
enabled_metadata=1

[dnlrn-infinality-ultimate-x86_64]
name=Copr repo for infinality-ultimate owned by dnlrn (x86_64)
baseurl=https://copr-be.cloud.fedoraproject.org/results/dnlrn/infinality-ultimate/fedora-$releasever-x86_64/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/dnlrn/infinality-ultimate/pubkey.gpg
enabled=1
enabled_metadata=1
```

After that, i386 packages are enabled, and the dependency resolution should automatically install the i386 infinality packages when you run "sudo dnf install steam". I know this is not perfect and I plan to edit my blogpost to notice users of these steps. Also, I plan to change from copr to OBS or my own hosted repo in the next few days, which should make all these problems go away. :)

**Comment by JHK** [comment]
Ah, great! worked, thank you!
