### ISSUE TITLE
Lines with monospaced fonts are too close in web pages.

### ISSUE THREAD

**Issue by decafbad** [drenninghoff/infinality-ultimate-fedora#5]
I couldn't find better words because of my english level.
I installed all libs, devel and font packages.
Take a look at this link: https://bugzilla.redhat.com/show_bug.cgi?id=1174893

Screenshot was taken with Google Chrome. In Firefox looks a little bit better. Chrome show page sources also like this.
![shot](https://cloud.githubusercontent.com/assets/1297145/12599057/6d5fe69a-c497-11e5-8a4d-67ca47dba556.png)

**Comment by danielrenninghoff** [comment]
Thanks for your report. I could reproduce your issue in Chrome. The font in question is Liberation Mono. This seems to be a Chrome-specific issue. What you can do to fix this is to switch to another font. In the Chrome font settings, switch the monospace font from "Monospace" to for example "DeJaVu Sans Mono". I will investigate this further and see if I can come up with a fix.

**Comment by kholia** [comment]
Thanks for reporting this. I am running into the same problem with Thunderbird, Chrome, and other applications as well.

**Comment by danielrenninghoff** [comment]
Okay, I found out, this is only happening with the latest version of the liberation-fonts (2.001). It doesn't happen when using the previous version (1.07.4). I'm guessing Chrome and Thunderbird use their own kind of font rendering that somehow doesn't work correctly. Tonight I'm going to roll back the liberation-fonts package to version 1.07.4. It should then be fixed! :)
