### ISSUE TITLE
Error in requesting URL

### ISSUE THREAD

**Issue by tathanhdinh** [drenninghoff/infinality-ultimate-fedora#6]
Many thanks for your infinality package. I just wonder if I can use it for my Fedora 21 (because of some reasons, I cannot upgrade my system to a newer version of Fedora). 

I have modified the field `BASE` in `Makefile` from `fedora-23` to `fedora-21`, then `make`; but there is an error (I think it does not comme from this modification) in downloading the font `Merriweather-HeavyItalic.ttf`:

```
Getting https://github.com/google/fonts/raw/master/ofl/merriweather/Merriweather-HeavyItalic.ttf to merriweather-ib-fonts/Merriweather-HeavyItalic.ttf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

Then the packaging cannot continue, it stops with report:

```
Makefile:17: recipe for target 'all' failed
make: *** [all] Error 22
```

**Comment by danielrenninghoff** [comment]
Hey, sorry about the inconvenience. I've changed the package and updated it to the newest version. :)
I've also included some instructions on how to currectly use the Makefile in the readme.md.

**Comment by tathanhdinh** [comment]
Many thanks @drenninghoff . I will try to recompile it, hope that I can get this package for my Fedora 21.
