### ISSUE TITLE
Unable to install infinality-bundle fonts on Fedora 24

### ISSUE THREAD

**Issue by kholia** [drenninghoff/infinality-ultimate-fedora#7]
```
$ sudo dnf install --allowerasing ibfonts-meta-base ibfonts-meta-extended-lt ibfonts-meta-extended
...
Error: Transaction check error:
  file /usr/share/fonts/tex-gyre from install of tex-gyre-ib-fonts-2.005-1.fc24.noarch conflicts with file from package texlive-tex-gyre-5:svn18651.2.004-24.fc24.1.noarch
```

**Comment by danielrenninghoff** [comment]
Thanks for the bugreport. Confirmed. This happens only on F24. I will fix it soon. In the meantime, just remove my package and use texlive-tex-gyre. It seems like on F24 it also provides the fonts for fontconfig.

**Comment by danielrenninghoff** [comment]
Should be fixed now. If the upgrade doesn't work, try removing ibfonts-meta-extended and ibfonts-meta-extended-lt and then installing them again.

Also, run `dnf clean metadata` if you can't find updates.

**Comment by kholia** [comment]
Thanks @drenninghoff, the bug is fixed now.
