### ISSUE TITLE
"dnf builddep wine" results in removal of various infinality packages

### ISSUE THREAD

**Issue by kholia** [drenninghoff/infinality-ultimate-fedora#8]
Running `sudo dnf builddep wine --allowerasing --best` on a Fedora 24 installation results in removal of various infinality packages. Running plain `sudo dnf builddep wine` aborts due to conflicts.

**Comment by danielrenninghoff** [comment]
I looked into this. I cant seem to fix it. This seems to be only happening when using dnf-builddep. The dependencies should be fine, so I don't understand why this is happening and can't fix it :(. Maybe a bug in dnf-builddep? If you have any idea, let me know.

**Comment by kholia** [comment]
I am out of ideas too but I will take a deeper look when I start some RPM packaging work again. Thanks!
