### ISSUE TITLE
ibfonts-meta-extended ibfonts-meta-extended-lt broken dependencies.

### ISSUE THREAD

**Issue by mydegeneration** [drenninghoff/infinality-ultimate-fedora#9]
OS: Fedora 24

Bug:

_$ sudo dnf update_ returns: "Skipping packages with broken dependencies:
 ibfonts-meta-extended     noarch  1-2.fc24   infinality-ultimate-noarch  6.0 k
 ibfonts-meta-extended-lt  noarch  1-2.fc24   infinality-ultimate-noarch  6.3 k
# Transaction Summary

Skip  2 Packages"

**Comment by danielrenninghoff** [comment]
I can't seem to reproduce this. I just tested this on a clean F24 install and I don't have any issues. Can you provide more details? Maybe you can try `sudo dnf update --debugsolver` and then provide the data as a zip for me?

**Comment by mydegeneration** [comment]
Here ya go 
[debugdata.zip](https://github.com/drenninghoff/infinality-ultimate-fedora/files/235229/debugdata.zip)

**Comment by mydegeneration** [comment]
I ended up removing and installing the packages again and everything worked just fine. Thanks! I truly appreciate your work :) :+1:
